//checklist
export const CHECKLIST_RECEIVED = 'CHECKLIST_RECEIVED';
export const TOGGLE_CHECKLIST = 'TOGGLE_CHECKLIST';

//rule set list
export const ALL_RULES_RECEIVED = 'ALL_RULES_RECEIVED';
export const ALL_SOBJECT_NAMES_RECEIVED = 'ALL_SOBJECT_NAMES_RECEIVED';
export const RULE_SET_TOGGLED = 'RULE_SET_TOGGLED';

//rules editor
export const ADD_ADVANCED_RULE = 'ADD_ADVANCED_RULE';
export const ADD_COMPLIANCE_RULE = 'ADD_COMPLIANCE_RULE';
export const CHANGE_ADVANCED_RULE_LOGIC = 'CHANGE_ADVANCED_RULE_LOGIC';
export const CHANGE_COMPLINACE_RULE_LOGIC = 'CHANGE_COMPLINACE_RULE_LOGIC';
export const CLEAR_RULE_SET_STATE = 'CLEAR_RULE_SET_STATE';
export const DELETE_ADVANCED_RULE = 'DELETE_ADVANCED_RULE';
export const DELETE_COMPLIANCE_RULE = 'DELETE_COMPLIANCE_RULE';
export const LICENSE_FIELDS_RECIEVED = 'LICENSE_FIELDS_RECIEVED';
export const RULE_SET_RESULT_RECEIVED = 'RULE_SET_RESULT_RECEIVED';
export const SAVED_RULE_SET_RESULT = 'SAVED_RULE_SET_RESULT';
export const SELECT_ADVANCED_CHANGE_RULE = 'SELECT_ADVANCED_CHANGE_RULE';
export const SELECT_CHANGE_RULE = 'SELECT_CHANGE_RULE';
export const SELECT_COMPLINACE_CHANGE_RULE = 'SELECT_COMPLINACE_CHANGE_RULE';
export const SHOW_ADVANCED_RULE = 'SHOW_ADVANCED_RULE';
export const SELECT_STATE_CHANGE_RULE = 'SELECT_STATE_CHANGE_RULE';
export const SOBJECT_FIELDS_RECIEVED = 'SOBJECT_FIELDS_RECIEVED';
export const TOGGLE_RESIDENT_RULE ='TOGGLE_RESIDENT_RULE';
export const HIDE_TOAST = 'HIDE_TOAST';

//csv LOAs
export const LINE_OF_AUTH_DELETED = 'LINE_OF_AUTH_DELETED';
export const LINES_OF_AUTH_INSERTED = 'LINES_OF_AUTH_INSERTED';
export const LINES_OF_AUTH_RECEIVED = 'LINES_OF_AUTH_RECEIVED';
export const OPEN_CSV = 'OPEN_CSV';
export const CANCEL_PREVIEW = 'CANCEL_PREVIEW';
