//checklist
export const CHECKLIST_RECEIVED = 'CHECKLIST_RECEIVED';
export const TOGGLE_CHECKLIST = 'TOGGLE_CHECKLIST';

//rule set list
export const ALL_RULES_RECEIVED = 'ALL_RULES_RECEIVED';
export const ALL_SOBJECT_NAMES_RECEIVED = 'ALL_SOBJECT_NAMES_RECEIVED';
export const RULE_SET_TOGGLED = 'RULE_SET_TOGGLED';

//rules editor
export const ADD_ADVANCED_RULE = 'ADD_ADVANCED_RULE';
export const ADD_COMPLIANCE_RULE = 'ADD_COMPLIANCE_RULE';
export const CHANGE_ADVANCED_RULE_LOGIC = 'CHANGE_ADVANCED_RULE_LOGIC';
export const CHANGE_COMPLINACE_RULE_LOGIC = 'CHANGE_COMPLINACE_RULE_LOGIC';
export const CLEAR_RULE_SET_STATE = 'CLEAR_RULE_SET_STATE';
export const DELETE_ADVANCED_RULE = 'DELETE_ADVANCED_RULE';
export const DELETE_COMPLIANCE_RULE = 'DELETE_COMPLIANCE_RULE';
export const LICENSE_FIELDS_RECIEVED = 'LICENSE_FIELDS_RECIEVED';
export const RULE_SET_RESULT_RECEIVED = 'RULE_SET_RESULT_RECEIVED';
export const SAVED_RULE_SET_RESULT = 'SAVED_RULE_SET_RESULT';
export const SELECT_ADVANCED_CHANGE_RULE = 'SELECT_ADVANCED_CHANGE_RULE';
export const SELECT_CHANGE_RULE = 'SELECT_CHANGE_RULE';
export const SELECT_COMPLINACE_CHANGE_RULE = 'SELECT_COMPLINACE_CHANGE_RULE';
export const SHOW_ADVANCED_RULE = 'SHOW_ADVANCED_RULE';
export const SELECT_STATE_CHANGE_RULE = 'SELECT_STATE_CHANGE_RULE';
export const SOBJECT_FIELDS_RECIEVED = 'SOBJECT_FIELDS_RECIEVED';
export const TOGGLE_RESIDENT_RULE ='TOGGLE_RESIDENT_RULE';
export const HIDE_TOAST = 'HIDE_TOAST';

//csv LOAs
export const LINE_OF_AUTH_DELETED = 'LINE_OF_AUTH_DELETED';
export const LINES_OF_AUTH_INSERTED = 'LINES_OF_AUTH_INSERTED';
export const LINES_OF_AUTH_RECEIVED = 'LINES_OF_AUTH_RECEIVED';
export const OPEN_CSV = 'OPEN_CSV';
export const CANCEL_PREVIEW = 'CANCEL_PREVIEW';
//NIPR-setup 
export const SET_NIPR_URL = 'SET_NIPR_URL';
export const SET_URL_ERROR='SET_URL_ERROR';
export const HEROKU_URL_CHANGE='HEROKU_URL_CHANGE';

//license approval rule
export const LICENSE_APPROVAL_RESULT_RECEIVED='LICENSE_APPROVAL_RESULT_RECEIVED';
export const LICENSE_APPROVAL_FIELDS_RESULT_RECEIVED='LICENSE_APPROVAL_FIELDS_RESULT_RECEIVED';
export const SELECT_LICENSE_CHANGE_RULE='SELECT_LICENSE_CHANGE_RULE';
export const ADD_LICENSE_RULE='ADD_LICENSE_RULE';
export const DELETE_LICENSE_RULE='DELETE_LICENSE_RULE';
export const CHANGE_LICENSE_RULE_LOGIC='CHANGE_LICENSE_RULE_LOGIC';
export const TOGGLE_FORCE_EXPIRE='TOGGLE_FORCE_EXPIRE';
export const TOGGLE_ACTIVATE_LICENSE='TOGGLE_ACTIVATE_LICENSE';
export const SAVE_LICENSE_APPROVAL_RULE='SAVE_LICENSE_APPROVAL_RULE';
export const ON_CHANGE_APPROVAL_PROCESS='ON_CHANGE_APPROVAL_PROCESS';
export const ON_VALIDATION_USER_RECEIVE='ON_VALIDATION_USER_RECEIVE';
export const ON_CHANGE_USER_SEARCH_STRING='ON_CHANGE_USER_SEARCH_STRING';
export const ON_APPROVAL_PROCESS_RECEIVE='ON_APPROVAL_PROCESS_RECEIVE';
export const CLEAR_USER_SEARCH_RESULT='CLEAR_USER_SEARCH_RESULT';
export const VALIDATION_USER_ERROR='VALIDATION_USER_ERROR';

// XML
export const XML_RECEIVED = 'XML_RECEIVED';
export const PRODUCERS_UPLOAD_INSERTED = 'PRODUCERS_UPLOAD_INSERTED';
export const SHOW_PROGRESS = 'SHOW_PROGRESS';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_STARTED = 'UPLOAD_STARTED';
export const IS_MAINTAINANCE_MODE ="IS_MAINTAINANCE_MODE";
export const UPLOAD_ERROR ="UPLOAD_ERROR";

export const SHOW_INVALID_TOAST = 'SHOW_INVALID_TOAST';
export const HIDE_INVALID_TOAST = 'HIDE_INVALID_TOAST';
export const SHOW_INVALID_DB_TOAST = 'SHOW_INVALID_DB_TOAST';
export const HIDE_INVALID_DB_TOAST = 'HIDE_INVALID_DB_TOAST';
export const SHOW_INVALID_FILE_TOAST = 'SHOW_INVALID_FILE_TOAST';
export const HIDE_INVALID_FILE_TOAST = 'HIDE_INVALID_FILE_TOAST';