import * as constants from '../constants/constants';

export default {
  advancedErrors:[],  
  advancedRuleLogic: {},
  advancedRulesList: [],
  allRuleSetResults: {},
  allSobjectNames: [],
  checklist: {},
  checklistComplete: false,
  complianceErrors:[],
  complianceRuleLogic: {},
  complianceRulesList: [],
  deletedLicenseRules: [],
  deletedRegularFilterRules: [],
  errors:false,
  fieldList: {},
  fileName: constants.CHOOSE_FILE,
  hideToast: false,
  isFilterRuleLogicRemoved: false,
  isLicenseRuleLogicRemoved: false,
  isReadOnly:false,
  licenseSobject: {},
  previewRows: [],
  residentRule: null,
  residentRuleOn:false,
  ruleSetResults: [],
  rulesList: {},
  sfdcRows: [],
  showAdvancedRule: "All",
  sobject: {},
  stateRule: {},
  xmlReceived: {},
  insertedProcedures: [],
  showProgress: false,
  showToast: false,
  niprShowUrl:false,
  niprSyncConfig:{},
  licencesRuleObject:{},
  licenseApprovalFileds:{},
  progressBarValue: 0,
  errorMessages: [],
  isLastBatch: false,
  licenseRuleLogic:{},
  validationUserList:[],
  validationUser:{},
  approvalProcessList:[],
  automatic_license_approval:false,
  herokuURLError: false,
  herokuURL: '',
  isMaintainanceMode: false,
  herokuURLSuccess: false,
  showInvalidToast: false,
  showInvalidDbToast: false,
  showInvalidFileToast: false,
  validationUserError:false,
};
