import * as constants from '../constants/constants';

export default {
  advancedErrors:[],  
  advancedRuleLogic: {},
  advancedRulesList: [],
  allRuleSetResults: {},
  allSobjectNames: [],
  checklist: {},
  checklistComplete: false,
  complianceErrors:[],
  complianceRuleLogic: {},
  complianceRulesList: [],
  deletedLicenseRules: [],
  deletedRegularFilterRules: [],
  errors:false,
  fieldList: {},
  fileName: constants.CHOOSE_FILE,
  hideToast: false,
  isFilterRuleLogicRemoved: false,
  isLicenseRuleLogicRemoved: false,
  isReadOnly:false,
  licenseSobject: {},
  previewRows: [],
  residentRule: null,
  residentRuleOn:false,
  ruleSetResults: [],
  rulesList: {},
  sfdcRows: [],
  showAdvancedRule: "All",
  sobject: {},
  stateRule: {},
  showToast: false,
};
